package com.calvin.oohw3.enums;

public enum ErrorType {
    EMPTYINPUT, INVALIDINPUT, INVALIDCHAR, SPACEINSIGNEDNUM,
    WRONGGRAMMAR, BRASYMISMATCH, LACKOPERATION, WRONGFORMATNUMBER,
    QUITTOOEARLY, WRONGSEG,
    WRONGTERMTYPEINLINKTERMS
}
